In [1]:
from sklearn import svm
   
from sklearn.svm import SVC
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('B2_heart.csv')
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
x=data.drop("target",axis=1)
y=data["target"]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.1)



In [5]:
from sklearn.svm import SVC
X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
Y=np.array([-1,-1,-1,1,1,1])
l=SVC(C=1e5,kernel='linear')
l.fit(X,Y)

SVC(C=100000.0, kernel='linear')

In [6]:
print('w=',l.coef_)
print('b=',l.intercept_)
print('indices of support vectors',l.support_)
print('support vectors',l.support_vectors_)
print('no.of support vectors from each class',l.n_support_)
print('coeff of support vectors in  decision function',np.abs(l.dual_coef_))

w= [[ 0.25 -0.25]]
b= [-0.75]
indices of support vectors [2 3]
support vectors [[ 2.  3.]
 [ 6. -1.]]
no.of support vectors from each class [1 1]
coeff of support vectors in  decision function [[0.0625 0.0625]]


In [7]:
linear=svm.SVC(kernel="linear")
linear.fit(X_train,Y_train)
print(linear.support_vectors_)
print(linear.n_support_)


[[60.  1.  2. ...  1.  0.  2.]
 [52.  1.  0. ...  1.  0.  0.]
 [54.  1.  1. ...  2.  1.  3.]
 ...
 [37.  1.  2. ...  0.  0.  2.]
 [66.  1.  0. ...  2.  0.  1.]
 [58.  1.  2. ...  1.  0.  3.]]
[51 55]


In [8]:
y_pred=linear.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print("accuracy",accuracy_score(Y_test,y_pred))
print("confusion matrix",confusion_matrix(Y_test,y_pred))
print("classification_report")
print(classification_report(Y_test,y_pred))


accuracy 0.8387096774193549
confusion matrix [[12  3]
 [ 2 14]]
classification_report
              precision    recall  f1-score   support

           0       0.86      0.80      0.83        15
           1       0.82      0.88      0.85        16

    accuracy                           0.84        31
   macro avg       0.84      0.84      0.84        31
weighted avg       0.84      0.84      0.84        31



In [17]:
model1=SVC(kernel='sigmoid')
model1.fit(X_train,Y_train)
y_pred1=model1.predict(X_test)

model2=SVC(kernel='poly')
model2.fit(X_train,Y_train)
y_pred2=model2.predict(X_test)

model3=SVC(kernel='rbf')
model3.fit(X_train,Y_train)
y_pred3=model3.predict(X_test)



In [18]:
print("prediction by model1",accuracy_score(Y_test,y_pred1))
print("prediction by model2",accuracy_score(Y_test,y_pred2))
print("prediction by model3",accuracy_score(Y_test,y_pred3))


prediction by model1 0.5161290322580645
prediction by model2 0.6451612903225806
prediction by model3 0.6451612903225806
